### ISSUE TITLE
Confused about the unit in `configuration` file

### ISSUE THREAD

**Issue by mizu-bai** [zhangylch/REANN#10]
I'm trying to train a model of my system (salty water, including two kinds of ions and water molecules) with EANN or REANN. The dataset was prepared by CP2K (we have no license for VASP), which is in the unit of Angstrom (Cartesian coordinates), Hartree/Bohr (Cartesian atomic forces), and Hartree (energy). Here are my questions:

1.  What are the units used in `configuration` file?
2. Is (R)EANN suitable for my system? Since I found that (R)EANN is popular in gas-solid scattering, but my system is for exploring gas-liquid scattering. Anyway, I could have a try and give you feedback.

Best wishes

**Comment by zhangylch** [comment]
> I'm trying to train a model of my system (salty water, including two kinds of ions and water molecules) with EANN or REANN. The dataset was prepared by CP2K (we have no license for VASP), which is in the unit of Angstrom (Cartesian coordinates), Hartree/Bohr (Cartesian atomic forces), and Hartree (energy). Here are my questions:
> 
> 1. What are the units used in `configuration` file?
> 2. Is (R)EANN suitable for my system? Since I found that (R)EANN is popular in gas-solid scattering, but my system is for exploring gas-liquid scattering. Anyway, I could have a try and give you feedback.
> 
> Best wishes

Thank you for your interest in our model!
The units in the configuration file are not specifically specified, they just need to be consistent. For example, if the coordinates are in angstroms and the energy is in eV, then the force must be in eV/angstrom.

Indeed we have not tested the gas-liquid system, but I believe it can be used to describe your system. Looking forward to your results.

Best,
Yaolong
