### ISSUE TITLE
example

### ISSUE THREAD

**Issue by yufengwhy** [zhangylch/REANN#3]
1. [`path="/home/home/zyl/pytorch/2021_8_1/eann-8/"`](https://github.com/zhangylch/REANN/blob/main/reann/example/co2%2Bni100/job-mpi.sh#L11)要如何修改？

2. 能不能加一个单机运行的example？
3. 方便share论文里面几个数据集吗？

**Comment by zhangylch** [comment]
> 1. [`path="/home/home/zyl/pytorch/2021_8_1/eann-8/"`](https://github.com/zhangylch/REANN/blob/main/reann/example/co2%2Bni100/job-mpi.sh#L11)要如何修改？
> 2. 能不能加一个单机运行的example？
> 3. 方便share论文里面几个数据集吗？

1. 存放程序的路径
2. example 里面就是单机运行的例子
3. 我们只能公开CO2+Ni100表面体系的数据，因为是我们自己的数据集，其他数据集都是他人公开的数据集，都有引用文献可以自行查找下载。

**Comment by yufengwhy** [comment]
> > 1. [`path="/home/home/zyl/pytorch/2021_8_1/eann-8/"`](https://github.com/zhangylch/REANN/blob/main/reann/example/co2%2Bni100/job-mpi.sh#L11)要如何修改？
> > 2. 能不能加一个单机运行的example？
> > 3. 方便share论文里面几个数据集吗？
> 
> 1. 存放程序的路径
> 2. example 里面就是单机运行的例子
> 3. 我们只能公开CO2+Ni100表面体系的数据，因为是我们自己的数据集，其他数据集都是他人公开的数据集，都有引用文献可以自行查找下载。

这个报错遇到过吗？能不能不用分布式？
Traceback (most recent call last):
  File "/data00/git/REANN/reann/example/co2+ni100/../../__main__.py", line 1, in <module>
    import run.train
  File "/data00/git/REANN/reann/run/train.py", line 3, in <module>
    from src.read import *
  File "/data00/git/REANN/reann/src/read.py", line 176, in <module>
    dist.init_process_group(backend=DDP_backend)
  File "/data00/anaconda3/envs/egnn/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 500, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/data00/anaconda3/envs/egnn/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 190, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: connect() timed out.

**Comment by zhangylch** [comment]
> > > 1. [`path="/home/home/zyl/pytorch/2021_8_1/eann-8/"`](https://github.com/zhangylch/REANN/blob/main/reann/example/co2%2Bni100/job-mpi.sh#L11)要如何修改？
> > > 2. 能不能加一个单机运行的example？
> > > 3. 方便share论文里面几个数据集吗？
> > 
> > 
> > 
> > 1. 存放程序的路径
> > 2. example 里面就是单机运行的例子
> > 3. 我们只能公开CO2+Ni100表面体系的数据，因为是我们自己的数据集，其他数据集都是他人公开的数据集，都有引用文献可以自行查找下载。
> 
> 这个报错遇到过吗？能不能不用分布式？ Traceback (most recent call last): File "/data00/git/REANN/reann/example/co2+ni100/../../**main**.py", line 1, in import run.train File "/data00/git/REANN/reann/run/train.py", line 3, in from src.read import * File "/data00/git/REANN/reann/src/read.py", line 176, in dist.init_process_group(backend=DDP_backend) File "/data00/anaconda3/envs/egnn/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 500, in init_process_group store, rank, world_size = next(rendezvous_iterator) File "/data00/anaconda3/envs/egnn/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 190, in _env_rendezvous_handler store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout) RuntimeError: connect() timed out.

CPU 上跑的吗？

**Comment by yufengwhy** [comment]
现在的出错是指定了一块gpu

**Comment by zhangylch** [comment]
出错原因已找到，没有在分布式下启动程序
