### ISSUE TITLE
EANN能否同时训练多个体系？

### ISSUE THREAD

**Issue by Romarin87** [zhangylch/REANN#5]
如何用REANN训练多个体系的数据？这些体系拥有不同数目和种类的原子。
我已经尝试过将两个体系的数据写在一个configuration中，或者分别将两个体系放在两个文件夹中，将路径写入input_nn，都没有成功。

**Comment by zhangylch** [comment]
> 如何用REANN训练多个体系的数据？这些体系拥有不同数目和种类的原子。 我已经尝试过将两个体系的数据写在一个configuration中，或者分别将两个体系放在两个文件夹中，将路径写入input_nn，都没有成功

将不同的体系写入configuration 是可以的，我们有过大量的测试

**Comment by Romarin87** [comment]
> > 如何用REANN训练多个体系的数据？这些体系拥有不同数目和种类的原子。 我已经尝试过将两个体系的数据写在一个configuration中，或者分别将两个体系放在两个文件夹中，将路径写入input_nn，都没有成功
> 
> 将不同的体系写入configuration 是可以的，我们有过大量的测试

解决了，是input文件参数设置错误，感谢！
