### ISSUE TITLE
训练模型时内存占用过大导致无法训练

### ISSUE THREAD

**Issue by Romarin87** [zhangylch/REANN#6]
你好，我想用reann训练一个比较大的数据集，但是在集群上训练，报了内存错误：RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 300486697920 bytes. Error code 12 (Cannot allocate memory)
因为集群上只有256GB内存，我猜测是数据集太大了，就更换了一个不到500MB的数据集，可以成功训练了，但是占用了将近20GB的内存，这个内存占用是不是我参数设置的有问题？如果我现在想要训练那个大的数据集（17GB左右，大约900w个结构），有什么办法可以实现吗？

下面是我的参数设置，是我直接在example基础上修改的：

```
**input_nn**
# required parameters 
  start_table = 1                # start_table table for the fit with force(1) or without force(0)
                                 # start_table table for DM(2), TDM(3), polarizability(4)
  table_coor = 0                 # table_coor   0 for cartesian coordinates and 1 for direct coordinates
  nl = [64,64]          # neural network architecture   
 # nl = [512,512,512,512]          # neural network architecture   
  nblock =  1
  dropout_p=[0.0,0.0,0.0,0.0]
  table_init = 0             # 1 used for load parameters from pth 
  nkpoint=1                      # number of nkpoint NNs was employed to representation polarizability
# NN epoch and NN optimize parameters
  Epoch=20000                    # max iterations epoch                 
  patience_epoch = 200            # pre initial learning rate epoch   
  decay_factor = 0.5             # Factor by which the learning rate will be reduced. new_lr = lr * factor.
  start_lr = 0.001               # initial learning rate
  end_lr =1e-5                  # final learning rate
  re_ceff = 0                # factor for regularization
# wave epoch and wave optimize parameters
  ratio = 0.9                    # ratio for training
# =====================================================================
  batchsize_train = 128                # batch_size
  batchsize_test = 256                # batch_size
  e_ceff=0.1
  init_f=50                     # init_f
  final_f=0.5                     # final_f
#========================queue_size sequence for laod data into gpu
  queue_size=10
  print_epoch=5
  table_norm=True
  DDP_backend='nccl' 
  activate = 'Relu_like'
  dtype="float32"
#===========param for orbital coefficient ===============================================
     oc_nl = [64,64]          # neural network architecture   
     oc_nblock = 1
     oc_dropout_p=[0,0,0,0]
     oc_activate = 'Relu_like'
   #========================queue_size sequence for laod data into gpu
     oc_table_norm=True
     oc_loop=3
#========================floder used to save the data========================
  floder="/home/bwli/t1x_train/reann/"


**input_density**
#==============param for atomic energy=======================
  neigh_atoms=60
  cutoff=6e0
  nipsin=2
  atomtype=['H', 'C', 'N', 'O']
  nwave=7
```

**Comment by zhangylch** [comment]
> 你好，我想用reann训练一个比较大的数据集，但是在集群上训练，报了内存错误：RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 300486697920 bytes. Error code 12 (Cannot allocate memory) 因为集群上只有256GB内存，我猜测是数据集太大了，就更换了一个不到500MB的数据集，可以成功训练了，但是占用了将近20GB的内存，这个内存占用是不是我参数设置的有问题？如果我现在想要训练那个大的数据集（17GB左右，大约900w个结构），有什么办法可以实现吗？
> 
> 下面是我的参数设置，是我直接在example基础上修改的：
> 
> ```
> **input_nn**
> # required parameters 
>   start_table = 1                # start_table table for the fit with force(1) or without force(0)
>                                  # start_table table for DM(2), TDM(3), polarizability(4)
>   table_coor = 0                 # table_coor   0 for cartesian coordinates and 1 for direct coordinates
>   nl = [64,64]          # neural network architecture   
>  # nl = [512,512,512,512]          # neural network architecture   
>   nblock =  1
>   dropout_p=[0.0,0.0,0.0,0.0]
>   table_init = 0             # 1 used for load parameters from pth 
>   nkpoint=1                      # number of nkpoint NNs was employed to representation polarizability
> # NN epoch and NN optimize parameters
>   Epoch=20000                    # max iterations epoch                 
>   patience_epoch = 200            # pre initial learning rate epoch   
>   decay_factor = 0.5             # Factor by which the learning rate will be reduced. new_lr = lr * factor.
>   start_lr = 0.001               # initial learning rate
>   end_lr =1e-5                  # final learning rate
>   re_ceff = 0                # factor for regularization
> # wave epoch and wave optimize parameters
>   ratio = 0.9                    # ratio for training
> # =====================================================================
>   batchsize_train = 128                # batch_size
>   batchsize_test = 256                # batch_size
>   e_ceff=0.1
>   init_f=50                     # init_f
>   final_f=0.5                     # final_f
> #========================queue_size sequence for laod data into gpu
>   queue_size=10
>   print_epoch=5
>   table_norm=True
>   DDP_backend='nccl' 
>   activate = 'Relu_like'
>   dtype="float32"
> #===========param for orbital coefficient ===============================================
>      oc_nl = [64,64]          # neural network architecture   
>      oc_nblock = 1
>      oc_dropout_p=[0,0,0,0]
>      oc_activate = 'Relu_like'
>    #========================queue_size sequence for laod data into gpu
>      oc_table_norm=True
>      oc_loop=3
> #========================floder used to save the data========================
>   floder="/home/bwli/t1x_train/reann/"
> 
> 
> **input_density**
> #==============param for atomic energy=======================
>   neigh_atoms=60
>   cutoff=6e0
>   nipsin=2
>   atomtype=['H', 'C', 'N', 'O']
>   nwave=7
> ```

你好，因为为了加速训练流程，减少比必要的额外开销。我们的模型是将数据全部读入内存中，然后计算了每个原子的neigh_list保存在内存中。有两种我认为是可行的方式 1. 我看了下你的atom_type应该是一些分子体系，能否简单描述下你的体系，如何体 可以的话那样的话你用了oc_loop=3（使用了MPNN）,你可以将你的cutoff减小（因为MPNN可以描述部分长程的性质），这样将neigh_atoms减小值15左右，这样内存消耗会减少1/4，结合你上面有一个申请了300GB内存，应该能行。第二种可行的方式，我们的程序支持跨节点，这样内存消耗就会分散的不同的节点上，可以有效的解决这个问题

**Comment by zhangylch** [comment]
> 你好，我想用reann训练一个比较大的数据集，但是在集群上训练，报了内存错误：RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 300486697920 bytes. Error code 12 (Cannot allocate memory) 因为集群上只有256GB内存，我猜测是数据集太大了，就更换了一个不到500MB的数据集，可以成功训练了，但是占用了将近20GB的内存，这个内存占用是不是我参数设置的有问题？如果我现在想要训练那个大的数据集（17GB左右，大约900w个结构），有什么办法可以实现吗？
> 
> 下面是我的参数设置，是我直接在example基础上修改的：
> 
> ```
> **input_nn**
> # required parameters 
>   start_table = 1                # start_table table for the fit with force(1) or without force(0)
>                                  # start_table table for DM(2), TDM(3), polarizability(4)
>   table_coor = 0                 # table_coor   0 for cartesian coordinates and 1 for direct coordinates
>   nl = [64,64]          # neural network architecture   
>  # nl = [512,512,512,512]          # neural network architecture   
>   nblock =  1
>   dropout_p=[0.0,0.0,0.0,0.0]
>   table_init = 0             # 1 used for load parameters from pth 
>   nkpoint=1                      # number of nkpoint NNs was employed to representation polarizability
> # NN epoch and NN optimize parameters
>   Epoch=20000                    # max iterations epoch                 
>   patience_epoch = 200            # pre initial learning rate epoch   
>   decay_factor = 0.5             # Factor by which the learning rate will be reduced. new_lr = lr * factor.
>   start_lr = 0.001               # initial learning rate
>   end_lr =1e-5                  # final learning rate
>   re_ceff = 0                # factor for regularization
> # wave epoch and wave optimize parameters
>   ratio = 0.9                    # ratio for training
> # =====================================================================
>   batchsize_train = 128                # batch_size
>   batchsize_test = 256                # batch_size
>   e_ceff=0.1
>   init_f=50                     # init_f
>   final_f=0.5                     # final_f
> #========================queue_size sequence for laod data into gpu
>   queue_size=10
>   print_epoch=5
>   table_norm=True
>   DDP_backend='nccl' 
>   activate = 'Relu_like'
>   dtype="float32"
> #===========param for orbital coefficient ===============================================
>      oc_nl = [64,64]          # neural network architecture   
>      oc_nblock = 1
>      oc_dropout_p=[0,0,0,0]
>      oc_activate = 'Relu_like'
>    #========================queue_size sequence for laod data into gpu
>      oc_table_norm=True
>      oc_loop=3
> #========================floder used to save the data========================
>   floder="/home/bwli/t1x_train/reann/"
> 
> 
> **input_density**
> #==============param for atomic energy=======================
>   neigh_atoms=60
>   cutoff=6e0
>   nipsin=2
>   atomtype=['H', 'C', 'N', 'O']
>   nwave=7
> ```

另外几个小的参数设置的建议，如果体系确实复杂需要用到[512,512,512,512]这么大的网络结构，建议使用[128,128]然后增加nblock，增加残差模块的数量来提高网络复杂度。一般来说效果会好。另外因为使用了MPNN，有可能你并不需要使用这么大的网络结构。此外如果数据量足够大的话（因为你有900W）,建议你减少patience_epoch，增加batch_size来加速训练

**Comment by Romarin87** [comment]
> > 你好，我想用reann训练一个比较大的数据集，但是在集群上训练，报了内存错误：RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 300486697920 bytes. Error code 12 (Cannot allocate memory) 因为集群上只有256GB内存，我猜测是数据集太大了，就更换了一个不到500MB的数据集，可以成功训练了，但是占用了将近20GB的内存，这个内存占用是不是我参数设置的有问题？如果我现在想要训练那个大的数据集（17GB左右，大约900w个结构），有什么办法可以实现吗？
> > 下面是我的参数设置，是我直接在example基础上修改的：
> > ```
> > **input_nn**
> > # required parameters 
> >   start_table = 1                # start_table table for the fit with force(1) or without force(0)
> >                                  # start_table table for DM(2), TDM(3), polarizability(4)
> >   table_coor = 0                 # table_coor   0 for cartesian coordinates and 1 for direct coordinates
> >   nl = [64,64]          # neural network architecture   
> >  # nl = [512,512,512,512]          # neural network architecture   
> >   nblock =  1
> >   dropout_p=[0.0,0.0,0.0,0.0]
> >   table_init = 0             # 1 used for load parameters from pth 
> >   nkpoint=1                      # number of nkpoint NNs was employed to representation polarizability
> > # NN epoch and NN optimize parameters
> >   Epoch=20000                    # max iterations epoch                 
> >   patience_epoch = 200            # pre initial learning rate epoch   
> >   decay_factor = 0.5             # Factor by which the learning rate will be reduced. new_lr = lr * factor.
> >   start_lr = 0.001               # initial learning rate
> >   end_lr =1e-5                  # final learning rate
> >   re_ceff = 0                # factor for regularization
> > # wave epoch and wave optimize parameters
> >   ratio = 0.9                    # ratio for training
> > # =====================================================================
> >   batchsize_train = 128                # batch_size
> >   batchsize_test = 256                # batch_size
> >   e_ceff=0.1
> >   init_f=50                     # init_f
> >   final_f=0.5                     # final_f
> > #========================queue_size sequence for laod data into gpu
> >   queue_size=10
> >   print_epoch=5
> >   table_norm=True
> >   DDP_backend='nccl' 
> >   activate = 'Relu_like'
> >   dtype="float32"
> > #===========param for orbital coefficient ===============================================
> >      oc_nl = [64,64]          # neural network architecture   
> >      oc_nblock = 1
> >      oc_dropout_p=[0,0,0,0]
> >      oc_activate = 'Relu_like'
> >    #========================queue_size sequence for laod data into gpu
> >      oc_table_norm=True
> >      oc_loop=3
> > #========================floder used to save the data========================
> >   floder="/home/bwli/t1x_train/reann/"
> > 
> > 
> > **input_density**
> > #==============param for atomic energy=======================
> >   neigh_atoms=60
> >   cutoff=6e0
> >   nipsin=2
> >   atomtype=['H', 'C', 'N', 'O']
> >   nwave=7
> > ```
> 
> 你好，因为为了加速训练流程，减少比必要的额外开销。我们的模型是将数据全部读入内存中，然后计算了每个原子的neigh_list保存在内存中。有两种我认为是可行的方式 1. 我看了下你的atom_type应该是一些分子体系，能否简单描述下你的体系，如何体 可以的话那样的话你用了oc_loop=3（使用了MPNN）,你可以将你的cutoff减小（因为MPNN可以描述部分长程的性质），这样将neigh_atoms减小值15左右，这样内存消耗会减少1/4，结合你上面有一个申请了300GB内存，应该能行。第二种可行的方式，我们的程序支持跨节点，这样内存消耗就会分散的不同的节点上，可以有效的解决这个问题

我这边的体系都是七个重原子以下的有机反应，原子数比较少，所以我觉得修改cutoff效果可能不会特别明显，我这边把机器做了个虚拟内存，最后大概读写了四百多GB，现在开始训练了。

**Comment by Romarin87** [comment]
> > 你好，我想用reann训练一个比较大的数据集，但是在集群上训练，报了内存错误：RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 300486697920 bytes. Error code 12 (Cannot allocate memory) 因为集群上只有256GB内存，我猜测是数据集太大了，就更换了一个不到500MB的数据集，可以成功训练了，但是占用了将近20GB的内存，这个内存占用是不是我参数设置的有问题？如果我现在想要训练那个大的数据集（17GB左右，大约900w个结构），有什么办法可以实现吗？
> > 下面是我的参数设置，是我直接在example基础上修改的：
> > ```
> > **input_nn**
> > # required parameters 
> >   start_table = 1                # start_table table for the fit with force(1) or without force(0)
> >                                  # start_table table for DM(2), TDM(3), polarizability(4)
> >   table_coor = 0                 # table_coor   0 for cartesian coordinates and 1 for direct coordinates
> >   nl = [64,64]          # neural network architecture   
> >  # nl = [512,512,512,512]          # neural network architecture   
> >   nblock =  1
> >   dropout_p=[0.0,0.0,0.0,0.0]
> >   table_init = 0             # 1 used for load parameters from pth 
> >   nkpoint=1                      # number of nkpoint NNs was employed to representation polarizability
> > # NN epoch and NN optimize parameters
> >   Epoch=20000                    # max iterations epoch                 
> >   patience_epoch = 200            # pre initial learning rate epoch   
> >   decay_factor = 0.5             # Factor by which the learning rate will be reduced. new_lr = lr * factor.
> >   start_lr = 0.001               # initial learning rate
> >   end_lr =1e-5                  # final learning rate
> >   re_ceff = 0                # factor for regularization
> > # wave epoch and wave optimize parameters
> >   ratio = 0.9                    # ratio for training
> > # =====================================================================
> >   batchsize_train = 128                # batch_size
> >   batchsize_test = 256                # batch_size
> >   e_ceff=0.1
> >   init_f=50                     # init_f
> >   final_f=0.5                     # final_f
> > #========================queue_size sequence for laod data into gpu
> >   queue_size=10
> >   print_epoch=5
> >   table_norm=True
> >   DDP_backend='nccl' 
> >   activate = 'Relu_like'
> >   dtype="float32"
> > #===========param for orbital coefficient ===============================================
> >      oc_nl = [64,64]          # neural network architecture   
> >      oc_nblock = 1
> >      oc_dropout_p=[0,0,0,0]
> >      oc_activate = 'Relu_like'
> >    #========================queue_size sequence for laod data into gpu
> >      oc_table_norm=True
> >      oc_loop=3
> > #========================floder used to save the data========================
> >   floder="/home/bwli/t1x_train/reann/"
> > 
> > 
> > **input_density**
> > #==============param for atomic energy=======================
> >   neigh_atoms=60
> >   cutoff=6e0
> >   nipsin=2
> >   atomtype=['H', 'C', 'N', 'O']
> >   nwave=7
> > ```
> 
> 另外几个小的参数设置的建议，如果体系确实复杂需要用到[512,512,512,512]这么大的网络结构，建议使用[128,128]然后增加nblock，增加残差模块的数量来提高网络复杂度。一般来说效果会好。另外因为使用了MPNN，有可能你并不需要使用这么大的网络结构。此外如果数据量足够大的话（因为你有900W）,建议你减少patience_epoch，增加batch_size来加速训练

非常感谢你的建议！！我现在并没有使用[512,512,512,512]这个网络结构，而是[64,64] ，目前打算按照你的建议把patience_epoch减少，batch_size增加，先训练一下，看下效果。

**Comment by zhangylch** [comment]
> > > 你好，我想用reann训练一个比较大的数据集，但是在集群上训练，报了内存错误：RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 300486697920 bytes. Error code 12 (Cannot allocate memory) 因为集群上只有256GB内存，我猜测是数据集太大了，就更换了一个不到500MB的数据集，可以成功训练了，但是占用了将近20GB的内存，这个内存占用是不是我参数设置的有问题？如果我现在想要训练那个大的数据集（17GB左右，大约900w个结构），有什么办法可以实现吗？
> > > 下面是我的参数设置，是我直接在example基础上修改的：
> > > ```
> > > **input_nn**
> > > # required parameters 
> > >   start_table = 1                # start_table table for the fit with force(1) or without force(0)
> > >                                  # start_table table for DM(2), TDM(3), polarizability(4)
> > >   table_coor = 0                 # table_coor   0 for cartesian coordinates and 1 for direct coordinates
> > >   nl = [64,64]          # neural network architecture   
> > >  # nl = [512,512,512,512]          # neural network architecture   
> > >   nblock =  1
> > >   dropout_p=[0.0,0.0,0.0,0.0]
> > >   table_init = 0             # 1 used for load parameters from pth 
> > >   nkpoint=1                      # number of nkpoint NNs was employed to representation polarizability
> > > # NN epoch and NN optimize parameters
> > >   Epoch=20000                    # max iterations epoch                 
> > >   patience_epoch = 200            # pre initial learning rate epoch   
> > >   decay_factor = 0.5             # Factor by which the learning rate will be reduced. new_lr = lr * factor.
> > >   start_lr = 0.001               # initial learning rate
> > >   end_lr =1e-5                  # final learning rate
> > >   re_ceff = 0                # factor for regularization
> > > # wave epoch and wave optimize parameters
> > >   ratio = 0.9                    # ratio for training
> > > # =====================================================================
> > >   batchsize_train = 128                # batch_size
> > >   batchsize_test = 256                # batch_size
> > >   e_ceff=0.1
> > >   init_f=50                     # init_f
> > >   final_f=0.5                     # final_f
> > > #========================queue_size sequence for laod data into gpu
> > >   queue_size=10
> > >   print_epoch=5
> > >   table_norm=True
> > >   DDP_backend='nccl' 
> > >   activate = 'Relu_like'
> > >   dtype="float32"
> > > #===========param for orbital coefficient ===============================================
> > >      oc_nl = [64,64]          # neural network architecture   
> > >      oc_nblock = 1
> > >      oc_dropout_p=[0,0,0,0]
> > >      oc_activate = 'Relu_like'
> > >    #========================queue_size sequence for laod data into gpu
> > >      oc_table_norm=True
> > >      oc_loop=3
> > > #========================floder used to save the data========================
> > >   floder="/home/bwli/t1x_train/reann/"
> > > 
> > > 
> > > **input_density**
> > > #==============param for atomic energy=======================
> > >   neigh_atoms=60
> > >   cutoff=6e0
> > >   nipsin=2
> > >   atomtype=['H', 'C', 'N', 'O']
> > >   nwave=7
> > > ```
> > 
> > 
> > 另外几个小的参数设置的建议，如果体系确实复杂需要用到[512,512,512,512]这么大的网络结构，建议使用[128,128]然后增加nblock，增加残差模块的数量来提高网络复杂度。一般来说效果会好。另外因为使用了MPNN，有可能你并不需要使用这么大的网络结构。此外如果数据量足够大的话（因为你有900W）,建议你减少patience_epoch，增加batch_size来加速训练
> 
> 非常感谢你的建议！！我现在并没有使用[512,512,512,512]这个网络结构，而是[64,64] ，目前打算按照你的建议把patience_epoch减少，batch_size增加，先训练一下，看下效果。

厉害！不过这样的体系，你neigh_atoms不需要取的那么大，因为你6A的截断半径应该取不到60个近邻原子，改成30甚至20应该足够了，可能你体系里面分子最多的原子都不超过30吧。 这样你不需要虚拟内存也能运行了。

**Comment by Romarin87** [comment]
> > > > 你好，我想用reann训练一个比较大的数据集，但是在集群上训练，报了内存错误：RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 300486697920 bytes. Error code 12 (Cannot allocate memory) 因为集群上只有256GB内存，我猜测是数据集太大了，就更换了一个不到500MB的数据集，可以成功训练了，但是占用了将近20GB的内存，这个内存占用是不是我参数设置的有问题？如果我现在想要训练那个大的数据集（17GB左右，大约900w个结构），有什么办法可以实现吗？
> > > 
> > > 
> > > 另外几个小的参数设置的建议，如果体系确实复杂需要用到[512,512,512,512]这么大的网络结构，建议使用[128,128]然后增加nblock，增加残差模块的数量来提高网络复杂度。一般来说效果会好。另外因为使用了MPNN，有可能你并不需要使用这么大的网络结构。此外如果数据量足够大的话（因为你有900W）,建议你减少patience_epoch，增加batch_size来加速训练
> > 
> > 
> > 非常感谢你的建议！！我现在并没有使用[512,512,512,512]这个网络结构，而是[64,64] ，目前打算按照你的建议把patience_epoch减少，batch_size增加，先训练一下，看下效果。
> 
> 厉害！不过这样的体系，你neigh_atoms不需要取的那么大，因为你6A的截断半径应该取不到60个近邻原子，改成30甚至20应该足够了，可能你体系里面分子最多的原子都不超过30吧。 这样你不需要虚拟内存也能运行了。

原来是这样！我之前看手册的neigh_atoms写的是’截断半径内最多包含的邻近原子数‘，觉得可能对于小体系来说，60和30都能覆盖到所有原子，应该没有影响，现在想想，是不是无论有多少个原子，在生成邻近列表的时候，为了便于处理，都会产生包含60个原子的变量？也就是里面会有很多空的值，估计这些数据里很大一部分都是空的。

**Comment by zhangylch** [comment]
> > > > > 你好，我想用reann训练一个比较大的数据集，但是在集群上训练，报了内存错误：RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 300486697920 bytes. Error code 12 (Cannot allocate memory) 因为集群上只有256GB内存，我猜测是数据集太大了，就更换了一个不到500MB的数据集，可以成功训练了，但是占用了将近20GB的内存，这个内存占用是不是我参数设置的有问题？如果我现在想要训练那个大的数据集（17GB左右，大约900w个结构），有什么办法可以实现吗？
> > > > 
> > > > 
> > > > 另外几个小的参数设置的建议，如果体系确实复杂需要用到[512,512,512,512]这么大的网络结构，建议使用[128,128]然后增加nblock，增加残差模块的数量来提高网络复杂度。一般来说效果会好。另外因为使用了MPNN，有可能你并不需要使用这么大的网络结构。此外如果数据量足够大的话（因为你有900W）,建议你减少patience_epoch，增加batch_size来加速训练
> > > 
> > > 
> > > 非常感谢你的建议！！我现在并没有使用[512,512,512,512]这个网络结构，而是[64,64] ，目前打算按照你的建议把patience_epoch减少，batch_size增加，先训练一下，看下效果。
> > 
> > 
> > 厉害！不过这样的体系，你neigh_atoms不需要取的那么大，因为你6A的截断半径应该取不到60个近邻原子，改成30甚至20应该足够了，可能你体系里面分子最多的原子都不超过30吧。 这样你不需要虚拟内存也能运行了。
> 
> 原来是这样！我之前看手册的neigh_atoms写的是’截断半径内最多包含的邻近原子数‘，觉得可能对于小体系来说，60和30都能覆盖到所有原子，应该没有影响，现在想想，是不是无论有多少个原子，在生成邻近列表的时候，为了便于处理，都会产生包含60个原子的变量？也就是里面会有很多空的值，估计这些数据里很大一部分都是空的。

是的，因为要预先申请一块内存存储neigh atoms

**Comment by zhangylch** [comment]
> > > > > > 你好，我想用reann训练一个比较大的数据集，但是在集群上训练，报了内存错误：RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 300486697920 bytes. Error code 12 (Cannot allocate memory) 因为集群上只有256GB内存，我猜测是数据集太大了，就更换了一个不到500MB的数据集，可以成功训练了，但是占用了将近20GB的内存，这个内存占用是不是我参数设置的有问题？如果我现在想要训练那个大的数据集（17GB左右，大约900w个结构），有什么办法可以实现吗？
> > > > > 
> > > > > 
> > > > > 另外几个小的参数设置的建议，如果体系确实复杂需要用到[512,512,512,512]这么大的网络结构，建议使用[128,128]然后增加nblock，增加残差模块的数量来提高网络复杂度。一般来说效果会好。另外因为使用了MPNN，有可能你并不需要使用这么大的网络结构。此外如果数据量足够大的话（因为你有900W）,建议你减少patience_epoch，增加batch_size来加速训练
> > > > 
> > > > 
> > > > 非常感谢你的建议！！我现在并没有使用[512,512,512,512]这个网络结构，而是[64,64] ，目前打算按照你的建议把patience_epoch减少，batch_size增加，先训练一下，看下效果。
> > > 
> > > 
> > > 厉害！不过这样的体系，你neigh_atoms不需要取的那么大，因为你6A的截断半径应该取不到60个近邻原子，改成30甚至20应该足够了，可能你体系里面分子最多的原子都不超过30吧。 这样你不需要虚拟内存也能运行了。
> > 
> > 
> > 原来是这样！我之前看手册的neigh_atoms写的是’截断半径内最多包含的邻近原子数‘，觉得可能对于小体系来说，60和30都能覆盖到所有原子，应该没有影响，现在想想，是不是无论有多少个原子，在生成邻近列表的时候，为了便于处理，都会产生包含60个原子的变量？也就是里面会有很多空的值，估计这些数据里很大一部分都是空的。
> 
> 是的，因为要预先申请一块内存存储neigh list，不会影响计算速度但是会占用内存
