### ISSUE TITLE
Batched input inference

### ISSUE THREAD

**Issue by IZugec** [zhangylch/REANN#7]
Dear developers,

Once I have trained model I need to evaluate this model on millions of points. In order to efficiently calculate energies and forces I was thinking to use batched input and GPU. However, when I introduce batch dimension I get the following error
https://paste.ofcode.org/3bKCYPbUBhmmJYtfnLtjBhB

which means that inference routines do not accept batch dimension. I was wondering what would be the easiest way to overcome this. Maybe to use density and get_neigh from training routines?

Thanks in advance and best,
Ivan

**Comment by zhangylch** [comment]
> Dear developers,
> 
> Once I have trained model I need to evaluate this model on millions of points. In order to efficiently calculate energies and forces I was thinking to use batched input and GPU. However, when I introduce batch dimension I get the following error https://paste.ofcode.org/3bKCYPbUBhmmJYtfnLtjBhB
> 
> which means that inference routines do not accept batch dimension. I was wondering what would be the easiest way to overcome this. Maybe to use density and get_neigh from training routines?
> 
> Thanks in advance and best, Ivan

Hi, REANN do not accept the batch dimension. The easiest way to overcome is to use get_neigh and density from the training routines. Or you can put all configurations in the validation and then print the energy in the Property* class by runing a epcoh training. Another way is to switch to the FIREANN model (https://github.com/zhangylch/FIREANN) which is similar to the REANN but with a dimension of (electric field which is zero in your situation). FIREANN supports the batch dimension.

**Comment by IZugec** [comment]
"Or you can put all configurations in the validation and then print the energy in the Property* class by runing a epcoh training"
This did the trick!

Thanks a lot for such a quick reply.
Best,
Ivan
