### ISSUE TITLE
训练example如何使用gpu

### ISSUE THREAD

**Issue by Mu-Jinming** [zhangylch/REANN#8]
在训练example时，使用nvidia-smi看到gpu没有被使用。使用的命令是`python3 -m torch.distributed.run --nproc_per_node=2 --nnodes=1 --standalone "/home/jinming/REANN/REANN/reann/"`，请问在哪里指定使用gpu进行训练？

**Comment by zhangylch** [comment]
> 在训练example时，使用nvidia-smi看到gpu没有被使用。使用的命令是`python3 -m torch.distributed.run --nproc_per_node=2 --nnodes=1 --standalone "/home/jinming/REANN/REANN/reann/"`，请问在哪里指定使用gpu进行训练？

程序会自动寻找节点上空闲的卡进行训练

**Comment by Mu-Jinming** [comment]
多谢学长！重新配置完环境可以正常训练了。
